spring.datasource.url=jdbc:postgresql://localhost:5436/medschedule
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# A chave secreta agora será lida da variável de ambiente API_SECURITY_TOKEN_SECRET
# que é carregada a partir do arquivo .env. Se não encontrar, usa um valor padrão vazio para evitar erro de inicialização imediato,
# mas falhará na hora de gerar/validar tokens se o .env não for carregado corretamente depois.
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:}
